### PR TITLE
feat: update voting type and result section

### PR DESCRIPTION
**Pull request by tortrakul-won**
Screenshot 2023-10-28 at 00-16-37 Parliament Watch
Screenshot 2023-10-28 at 00-18-24 Parliament Watch

### CODE REVIEW

**Review by Th1nkK1D — CHANGES_REQUESTED** [review]
Hi! Sorry for the late review. Everything is looking like what we expected. But we already have `VotingOptionTag` and `VotingResultTag` components (take a look at https://parliament-watch.pages.dev/stories/) Please use these components instead to keep the consistency.

**Comment by tortrakul-won** [comment]
Ok, I have updated the page to use to components instead. Please check it to if it need further improvement.

**Review by Th1nkK1D — APPROVED** [review]
LGTM! Thank you for your contribution. We will contact you about the stickers soon.

**Comment by Th1nkK1D** [comment]
Thank you for the Hacktoberfest participation! Please fill up the [form](https://airtable.com/appgGYIo458vDkrQN/shrZMe2hZBa6tQXvz) before 6 November 2023 to receive our limited-edition stickers.

**Pull request merged**
