### PR TITLE
Change the license in about page

### PR DESCRIPTION
**Pull request by wannaphong**
It is Creative Commons Attribution-NonCommercial-ShareAlike  not Creative Commons Attribution-ShareAlike License because It can't commercial use. "สามารถนำไปเผยแพร่และดัดแปลงได้ โดยต้องระบุที่มา แต่ห้ามนำไปใช้เพื่อการค้า และต้องเผยแพร่งานดัดแปลงโดยใช้สัญญาอนุญาตชนิดเดียวกัน"

### CODE REVIEW

**Review by Th1nkK1D — COMMENTED** [review]
Nice catch! We just revised the license for WeVis project and I forget to change it here. Can you also help us use the full name and add link with `target="_blank"` like this: [Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International](https://creativecommons.org/licenses/by-nc-sa/4.0/)

**Comment by wannaphong** [comment]
> Nice catch! We just revised the license for WeVis project and I forget to change it here. Can you also help us use the full name and add link with `target="_blank"` like this: [Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International](https://creativecommons.org/licenses/by-nc-sa/4.0/)

Done

**Review by Th1nkK1D — APPROVED** [review]
LGTM! Thank you for the PR.

For the sticker, we will reach you for the logistic information when the campaign has ended ;)

**Comment by Th1nkK1D** [comment]
Thank you again for joining our Hacktoberfest 2024 campaign ✨

Please fill in this [form](https://docs.google.com/forms/d/e/1FAIpQLScxGfIfpz9BWOOPBabFQ2almCJK1fykl-hVZOnWJacpCuvsjQ/viewform) so we can send you the stickers as soon as possible.

**Pull request merged**
